### PR TITLE
Add configuration files for Kia Soul & Kia Soul EV

### PR DESCRIPTION
**Pull request by bbidault2**
Dear Apollo Team,

At [PolySync](https://github.com/PolySync), we just released a new version of our ROS node for DriveKit/[OSCC](https://github.com/PolySync/oscc), [ROSCCO](https://github.com/PolySync/roscco).

This new version of the node includes code to enable users to forward `/apollo/control` topic messages to their DriveKit/OSCC platform for Apollo to take control of their vehicle steering wheel, brake and throttle.
We now have multiple configuration files on hands for the Kia Soul and the Kia Soul EV that we would like to share with the community. 
In the future, we are planning on extending this work to the Kia Niro.

I was not able to successfully run `./apollo.sh check`, even on a clean, untouched version of master branch.
I would be interested to know what the licenses should look like since those are `.txt` files.

### CODE REVIEW

**Comment by Capri2014** [comment]
@bbidault2 Thanks! Any plans to share the Kia CAN interface code as well?

**Comment by bbidault2** [comment]
@Capri2014 what do you mean by "CAN interface code" ? What does it look like for the Lincoln MKZ ?
We have taken a different approach than the one recommended by Apollo's documentation. Instead of using a CAN card like the recommended CAN-PCIe/402, DriveKit/OSCC takes care of sending commands to the vehicle and ROSCCO serves as a bridge between DriveKit/OSCC and Apollo.
Some of the CAN specifications we gathered are available publicly on the [OSCC](https://github.com/PolySync/oscc) repository.

**Comment by Capri2014** [comment]
@bbidault2 It is totally fine to use different canard, but how about the vehicle protocols like ones in here `https://github.com/ApolloAuto/apollo/tree/master/modules/canbus/vehicle/lincoln/protocol` ? In general we want to have the new protocols and configurations files for new vehicles checked in at the same time. -- So the platform users can grab and go.

**Comment by lianglia-apollo** [comment]
We suggest put third party codes/configs to https://github.com/ApolloAuto/apollo-contrib.

**Comment by bbidault2** [comment]
@Capri2014 , we do not have protocol files and I understand how this could be inconvenient.
@lianglia-apollo that look like a great alternate place to make these files available to the community, I will close this PR and open a new one on this repository. In any case, the files are still available on our repository.

**Pull request closed without merging**
