### PR TITLE
clang format include categories

### PR DESCRIPTION
**Pull request by Fla3inH0tCheet0s**
clang-format 10 regroups and reorders includes. Also, cpplint 1.5 and above checks these includes more vigorously. It might be a good idea to leverage the tools to save time.

Below is an example formatted list.

```
#include <std_c_lib.h>

#include <iostream>
#include <string>

#include <cuda.h>
#include <experimental/asdf>
#include <linux/whatever>

#include "gmock/gmock.h"
#include "gtest/gtest.h"

#include "jsoncpp/json.h"
#include "somelib/somlib.h"

#include "modules/dreamview/proto/hmi_mode.pb.h"
#include "modules/localization/proto/localization.pb.h"

#include "cyber/common/log.h"
#include "modules/common/adapters/adapter_gflags.h"
#include "modules/planning/planning_base.h"
```

### CODE REVIEW

**Comment by storypku** [comment]
> vigorously

Thanks for PR! One question: For Apollo headers, why 

```
#include "modules/dreamview/proto/hmi_mode.pb.h"
#include "modules/localization/proto/localization.pb.h"

#include "cyber/common/log.h"
#include "modules/common/adapters/adapter_gflags.h"
#include "modules/planning/planning_base.h"
``

rather than

```
#include "cyber/common/log.h"
#include "modules/dreamview/proto/hmi_mode.pb.h"
#include "modules/localization/proto/localization.pb.h"
#include "modules/common/adapters/adapter_gflags.h"
#include "modules/planning/planning_base.h"
```

?

**Comment by Capri2014** [comment]
> clang-format 10 regroups and reorders includes. Also, cpplint 1.5 and above checks these includes more vigorously. It might be a good idea to leverage the tools to save time.
> 
> Below is an example formatted list.
> 
> ```
> #include <std_c_lib.h>
> 
> #include <iostream>
> #include <string>
> 
> #include <cuda.h>
> #include <experimental/asdf>
> #include <linux/whatever>
> 
> #include "gmock/gmock.h"
> #include "gtest/gtest.h"
> 
> #include "jsoncpp/json.h"
> #include "somelib/somlib.h"
> 
> #include "modules/dreamview/proto/hmi_mode.pb.h"
> #include "modules/localization/proto/localization.pb.h"
> 
> #include "cyber/common/log.h"
> #include "modules/common/adapters/adapter_gflags.h"
> #include "modules/planning/planning_base.h"
> ```

One quick question, what is the difference between the last two? 

```
#include "modules/dreamview/proto/hmi_mode.pb.h"
#include "modules/localization/proto/localization.pb.h"

#include "cyber/common/log.h"
#include "modules/common/adapters/adapter_gflags.h"
#include "modules/planning/planning_base.h"
```

or my two cents is for `modules/planning/planning_base.cpp`, it should be

```
#include "cyber/common/log.h"
#include "modules/common/adapters/adapter_gflags.h"
#include "modules/dreamview/proto/hmi_mode.pb.h"
#include "modules/localization/proto/localization.pb.h"

#include "modules/planning/planning_base.h"
```

**Comment by storypku** [comment]
> > clang-format 10 regroups and reorders includes. Also, cpplint 1.5 and above checks these includes more vigorously. It might be a good idea to leverage the tools to save time.
> > Below is an example formatted list.
> > ```
> > #include <std_c_lib.h>
> > 
> > #include <iostream>
> > #include <string>
> > 
> > #include <cuda.h>
> > #include <experimental/asdf>
> > #include <linux/whatever>
> > 
> > #include "gmock/gmock.h"
> > #include "gtest/gtest.h"
> > 
> > #include "jsoncpp/json.h"
> > #include "somelib/somlib.h"
> > 
> > #include "modules/dreamview/proto/hmi_mode.pb.h"
> > #include "modules/localization/proto/localization.pb.h"
> > 
> > #include "cyber/common/log.h"
> > #include "modules/common/adapters/adapter_gflags.h"
> > #include "modules/planning/planning_base.h"
> > ```
> 
> One quick question, what is the difference between the last two?
> 
> ```
> #include "modules/dreamview/proto/hmi_mode.pb.h"
> #include "modules/localization/proto/localization.pb.h"
> 
> #include "cyber/common/log.h"
> #include "modules/common/adapters/adapter_gflags.h"
> #include "modules/planning/planning_base.h"
> ```
> 
> or my two cents is for `modules/planning/planning_base.cpp`, it should be
> 
> ```
> #include "cyber/common/log.h"
> #include "modules/common/adapters/adapter_gflags.h"
> #include "modules/dreamview/proto/hmi_mode.pb.h"
> #include "modules/localization/proto/localization.pb.h"
> 
> #include "modules/planning/planning_base.h"
> ```

By our previous convection, header orders for `modules/planning/planning_base.cpp` should be

```
// corresponding header with same name first
#include "modules/planning/planning_base.h"

// cyber & modules headers
#include "cyber/common/log.h"
#include "modules/common/adapters/adapter_gflags.h"
#include "modules/dreamview/proto/hmi_mode.pb.h"
#include "modules/localization/proto/localization.pb.h"
```

So,  there are two points here.
1) Whether headers with the same name as the ".cc" file should be placed first.
2) Whether `protobuf` headers should form its own group.

Waiting for more discussions.

cc @xiaoxq

**Comment by Capri2014** [comment]
> > One quick question, what is the difference between the last two?
> > ```
> > #include "modules/dreamview/proto/hmi_mode.pb.h"
> > #include "modules/localization/proto/localization.pb.h"
> > 
> > #include "cyber/common/log.h"
> > #include "modules/common/adapters/adapter_gflags.h"
> > #include "modules/planning/planning_base.h"
> > ```
> > 
> > 
> > or my two cents is for `modules/planning/planning_base.cpp`, it should be
> > ```
> > #include "cyber/common/log.h"
> > #include "modules/common/adapters/adapter_gflags.h"
> > #include "modules/dreamview/proto/hmi_mode.pb.h"
> > #include "modules/localization/proto/localization.pb.h"
> > 
> > #include "modules/planning/planning_base.h"
> > ```
> 
> By our previous convection, header orders for `modules/planning/planning_base.cpp` should be
> 
> ```
> // corresponding header with same name first
> #include "modules/planning/planning_base.h"
> 
> // cyber & modules headers
> #include "cyber/common/log.h"
> #include "modules/common/adapters/adapter_gflags.h"
> #include "modules/dreamview/proto/hmi_mode.pb.h"
> #include "modules/localization/proto/localization.pb.h"
> ```
> 
> So, there are two points here.
> 
> 1. Whether headers with the same name as the ".cc" file should be placed first.
> 2. Whether `protobuf` headers should form its own group.
> 
> Waiting for more discussions.
> 
> cc @xiaoxq

oh, sorry, I was wrong in the format.

**Comment by Fla3inH0tCheet0s** [comment]
>So, there are two points here.
>
>Whether headers with the same name as the ".cc" file should be placed first.

FYI. Clang-format treats it that way by default. From https://clang.llvm.org/docs/ClangFormatStyleOptions.html,
> The main header for a source file automatically gets category 0.

This implementation is just my interpretation of what you have so far. I haven't tried applying it to all of the files.

**Comment by Fla3inH0tCheet0s** [comment]
There's a couple of gotchas that should be taken into account, since reordering includes changes how the files are compiled due to macros.

* opencv has some macros that conflict with Eigen, but it works if eigen is included first. So the sorting will help.
* Some versions of Eigen conflict with Fast-RTPS due to the `ALIVE` macro.
* ncurses conflicts with cyber due to the `OK` macro.
* openCV and flann conflict with PCL due to the `USE_UNORDERED_MAP` macro. https://github.com/mariusmuja/flann/issues/214

In practice adding `#undef` before the includes will allow the headers to compile.

**Comment by xiaoxq** [comment]
As this will change the behavior of clang-format, could you append a commit that re-format all files, or at least a module (such as cyber/...)? so that we can check if it works as expected and reasonable.

**Comment by Fla3inH0tCheet0s** [comment]
> could you append a commit that re-format all files, or at least a module (such as cyber/...)?

@xiaoxq I ran
```
clang-format -i cyber/**/*.cc cyber/**/*.h
```
to produce 6ef2698a9449dcbdfa7e6896e6aa64ad97eb2511. I'm afraid running it on the whole code base will produce too many changes. The biggest differences were adding a space between the C headers and the C++ ones, moving the protobuf headers to their own section, and moving gtest to its own section. I like the consistency, but feel free to change the style to your liking.

**Pull request merged**
