### PR TITLE
Canbus: num_ports=8 for HermesCAN and refactored setup_device logic

### PR DESCRIPTION
**Pull request by storypku**

### CODE REVIEW

**Comment by Capri2014** [comment]
Just to confirm, so we do not need to make can/nv node anymore? Just needs to check and warn???? Where do you do the node mapping then?

**Comment by storypku** [comment]
> Just to confirm, so we do not need to make can/nv node anymore? Just needs to check and warn???? Where do you do the node mapping then?

The nvidia nodes are listed as follows

```
 ll /dev/nvidia*
crw-rw-rw- 1 root root 195,   0 Dec  4 21:05 /dev/nvidia0
crw-rw-rw- 1 root root 195, 255 Dec  4 21:05 /dev/nvidiactl
crw-rw-rw- 1 root root 195, 254 Dec  4 21:05 /dev/nvidia-modeset
crw-rw-rw- 1 root root 235,   0 Dec  4 21:05 /dev/nvidia-uvm
crw-rw-rw- 1 root root 235,   1 Dec  4 21:05 /dev/nvidia-uvm-tools

/dev/nvidia-caps:
total 0
drwxr-xr-x  2 root root     80 Dec  4 21:06 ./
drwxr-xr-x 20 root root   4420 Dec  4 21:18 ../
cr--------  1 root root 238, 1 Dec  4 21:06 nvidia-cap1
cr--r--r--  1 root root 238, 2 Dec  4 21:06 nvidia-cap2
```

I had run `rm -r /dev/nvidia*` on my GPU-capable machine and reboot, the first 5 nodes were regenerated. So It seems that they were brought up by Nvidia driver, which means that we don't need to manually perform mknod operations on them.

Moreover, the major device number was 235 for nvidia-uvm rather than 243 before this PR.

**Comment by jinghaomiao** [comment]
> > Just to confirm, so we do not need to make can/nv node anymore? Just needs to check and warn???? Where do you do the node mapping then?
> 
> The nvidia nodes are listed as follows
> 
> ```
>  ll /dev/nvidia*
> crw-rw-rw- 1 root root 195,   0 Dec  4 21:05 /dev/nvidia0
> crw-rw-rw- 1 root root 195, 255 Dec  4 21:05 /dev/nvidiactl
> crw-rw-rw- 1 root root 195, 254 Dec  4 21:05 /dev/nvidia-modeset
> crw-rw-rw- 1 root root 235,   0 Dec  4 21:05 /dev/nvidia-uvm
> crw-rw-rw- 1 root root 235,   1 Dec  4 21:05 /dev/nvidia-uvm-tools
> 
> /dev/nvidia-caps:
> total 0
> drwxr-xr-x  2 root root     80 Dec  4 21:06 ./
> drwxr-xr-x 20 root root   4420 Dec  4 21:18 ../
> cr--------  1 root root 238, 1 Dec  4 21:06 nvidia-cap1
> cr--r--r--  1 root root 238, 2 Dec  4 21:06 nvidia-cap2
> ```
> 
> I had run `rm -r /dev/nvidia*` on my GPU-capable machine and reboot, the first 5 nodes were regenerated. So It seems that they were brought up by Nvidia driver, which means that we don't need to manually perform mknod operations on them.
> 
> Moreover, the major device number was 235 for nvidia-uvm rather than 243 before this PR.

Please double check if those nodes could be automatically created and launched with a fresh clean system.

**Comment by storypku** [comment]
> > > Just to confirm, so we do not need to make can/nv node anymore? Just needs to check and warn???? Where do you do the node mapping then?
> > 
> > 
> > The nvidia nodes are listed as follows
> > ```
> >  ll /dev/nvidia*
> > crw-rw-rw- 1 root root 195,   0 Dec  4 21:05 /dev/nvidia0
> > crw-rw-rw- 1 root root 195, 255 Dec  4 21:05 /dev/nvidiactl
> > crw-rw-rw- 1 root root 195, 254 Dec  4 21:05 /dev/nvidia-modeset
> > crw-rw-rw- 1 root root 235,   0 Dec  4 21:05 /dev/nvidia-uvm
> > crw-rw-rw- 1 root root 235,   1 Dec  4 21:05 /dev/nvidia-uvm-tools
> > 
> > /dev/nvidia-caps:
> > total 0
> > drwxr-xr-x  2 root root     80 Dec  4 21:06 ./
> > drwxr-xr-x 20 root root   4420 Dec  4 21:18 ../
> > cr--------  1 root root 238, 1 Dec  4 21:06 nvidia-cap1
> > cr--r--r--  1 root root 238, 2 Dec  4 21:06 nvidia-cap2
> > ```
> > 
> > 
> > I had run `rm -r /dev/nvidia*` on my GPU-capable machine and reboot, the first 5 nodes were regenerated. So It seems that they were brought up by Nvidia driver, which means that we don't need to manually perform mknod operations on them.
> > Moreover, the major device number was 235 for nvidia-uvm rather than 243 before this PR.
> 
> Please double check if those nodes could be automatically created and launched with a fresh clean system.

I did checked this before by removing all  nvidia-generated dkms under `/lib/modules/$(uname -r)/updates/dkms/nvidia`,
apt-get purge --remove nvidia-driver-xxx and reboot, these nodes were successfully regenerated.

**Review by Capri2014 — APPROVED** [review]

**Pull request merged**
