### PR TITLE
Fix typo in cyber.py Node.create_reader() comment

### PR DESCRIPTION
**Pull request by xqgex**

### CODE REVIEW

**Comment by xqgex** [comment]
> @xqgex Pls rebase the commit to fit https://www.conventionalcommits.org/en/v1.0.0/

Done

**Comment by daohu527** [comment]
You have 3 commits, and we'd better `git rebase` to one then format like
```
chore(cyber): fix typo in cyber.py
```

You can find more information on git rebase online

**Comment by xqgex** [comment]
@daohu527  Why don't you do squash and merge?
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/about-merge-methods-on-github

**Comment by daohu527** [comment]
squash and merge just merges the commit without changing the commit content

**Comment by xqgex** [comment]
@daohu527 I've rebased the forked branch on top of the latest origin `master` branch

**Comment by daohu527** [comment]
I see there are still 2 commits and here is an format example
```
chore(cyber): fix typo in cyber.py
```

**Pull request closed without merging**
