### PR TITLE
Fixed processor_id range overflow

### PR DESCRIPTION
**Pull request by daohu527**
#10902 

1. Fixed in "SchedulerChoreography::RemoveCRoutine", add a condition pid should less than processor num
2. Fixed in "SchedulerChoreography::NotifyProcessor",  add a condition pid should less than processor num, move the "pid = cr->processor_id();" in the lock block.

### CODE REVIEW

**Comment by jinghaomiao** [comment]
@daohu527 please fix lint error.

**Comment by lx18233184051** [comment]
build faild log：
[05:34:57]	____(04-07 05:34:57.230) [6,764 / 6,775] Testing //cyber/scheduler:scheduler_choreography_cpplint
[05:34:57]	FAIL: (04-07 05:34:57.592) //cyber/scheduler:scheduler_choreography_cpplint (see /home/apollo/.cache/bazel/_bazel_apollo/540135163923dd7d5820f3ee4b306b32/execroot/apollo/bazel-out/local-dbg/testlogs/cyber/scheduler/scheduler_choreography_cpplint/test.log)
[05:34:57]	____(04-07 05:34:57.597) From Testing //cyber/scheduler:scheduler_choreography_cpplint:

**Comment by daohu527** [comment]
thx! I am dealing with it.

**Comment by lx18233184051** [comment]
approve

**Pull request merged**
