### PR TITLE
Add Newton-M2 GPS to branch master

### PR DESCRIPTION
**Pull request by lishuanghua**
Add Newton-M2 GPS to branch master which is cherry-picked from branch v3.1_dev.

### CODE REVIEW

**Comment by lishuanghua** [comment]
> 
> 
> too much duplicated code with novatel parser，Is it better to add a new imu-type?

Newton-M2 is a new type GPS device and it is already merged into branch v3.1_dev and r3.0.0.

**Comment by vdjapic** [comment]
Where can I buy Newton-M2 GPS receiver?

**Comment by lishuanghua** [comment]
> 
> 
> Where can I buy Newton-M2 GPS receiver?

What's your email ?  I'd like to post you some information.

**Comment by vdjapic** [comment]
vdjapic@gmail.com

**Comment by vdjapic** [comment]
Please email me more information about the Newton M2 GNSS INS sensor.
Thanks.

**Pull request merged**
