### PR TITLE
Improve Conti radar preprocessor

### PR DESCRIPTION
**Pull request by pantonante**
Enable the Conti Radar pre-processor to handle obstacles ids in the whole range int32 (previously only in the range 0-99).
This fix enable the use of LGSVL's RADAR for obstacle detection.

### CODE REVIEW

**Comment by Capri2014** [comment]
> Enable the Conti Radar pre-processor to handle obstacles ids in the whole range int32 (previously only in the range 0-99).
> This fix enable the use of LGSVL's RADAR for obstacle detection.

I think this change makes sense, please rebase and resolve the conflict, thanks for contributing to Apollo!

**Comment by Capri2014** [comment]
@pantonante

**Comment by pantonante** [comment]
Sorry @Capri2014 I messed it up because I rebased to master, seems I cannot change the branch to which merge now. Do you mind if I close (and possibly delete this pull-request) and create another one?

**Comment by Capri2014** [comment]
> Sorry @Capri2014 I messed it up because I rebased to master, seems I cannot change the branch to which merge now. Do you mind if I close (and possibly delete this pull-request) and create another one?

please go ahead and do so.

**Pull request closed without merging**
