### PR TITLE
Enable LGSVL Simulator.

### PR DESCRIPTION
**Pull request by rongguodong**

### CODE REVIEW

**Comment by rongguodong** [comment]
This is already based on latest master pulled at tonight. Are there new commits there?

**Comment by Capri2014** [comment]
> This is already based on latest master pulled at tonight. Are there new commits there?

Then is it possible to break this pr into smaller commits? Otherwise it is almost impossible for us to finish the review  in a timely manner ..

**Comment by rongguodong** [comment]
> > This is already based on latest master pulled at tonight. Are there new commits there?
> 
> Then is it possible to break this pr into smaller commits? Otherwise it is almost impossible for us to finish the review in a timely manner ..

I have split it into five pull requests (11185/11186/11187/11188/11189) as suggested.

**Comment by lx18233184051** [comment]
//cyber/bridge:cyber_bridge_cpplint                                      FAILED

**Comment by xiaoxq** [comment]
Let's close this one and work on the small pull requests.

**Pull request closed without merging**
