### PR TITLE
LGSVL Simulator change (part 1)

### PR DESCRIPTION
**Pull request by rongguodong**
Add Borregas map

### CODE REVIEW

**Comment by Capri2014** [comment]
These might needs to be made as docker volume it you would like to contribute to Apollo, @xiaoxq @ycool Your thoughts?

**Comment by xiaoxq** [comment]
> These might needs to be made as docker volume it you would like to contribute to Apollo, @xiaoxq @ycool Your thoughts?

Thank you! These files are relatively small and I feel OK to check in directly :)

**Comment by xiaoxq** [comment]
Could you sign the CLA so that we can merge the PR. Thanks!

**Comment by rongguodong** [comment]
> Could you sign the CLA so that we can merge the PR. Thanks!

I clicked "details" beside `license/cla`, and clicked the button saying "sign in github to sign cla". Then it brings me back to this page, and nothing seems happened. :(

Can you guide me how to sign it correctly?

**Comment by rongguodong** [comment]
I click "details" beside license/cla now, it shows "You have signed the CLA for ApolloAuto/apollo". But this page still shows "Contributor License Agreement is not signed yet". Why?

**Pull request merged**
