### PR TITLE
correct start timestamp of planning component

### PR DESCRIPTION
**Pull request by lihaoxiang1989**
It makes no sense to have dt=0. And cause the optimizing algorithm is really time-consuming, a time shift is necessary.
I have tested it in several cases and got a better control output speed curve.

### CODE REVIEW

**Comment by lihaoxiang1989** [comment]
@qwetqwe @changsh726, please review this PR, thx

**Comment by qwetqwe** [comment]
Thanks for you PR. This may be a history bug. on_lane_planning has recorded start_timestamp:

> https://github.com/ApolloAuto/apollo/blob/e076feecb46232bacdf08490c5ff213832e6bdd8/modules/planning/on_lane_planning.cc#L131

 It will be better to change like this:
```cpp
  planning_base_->RunOnce(local_view_, &adc_trajectory_pb);
  auto start_time = adc_trajectory_pb.header().timestamp_sec();
  common::util::FillHeader(node_->Name(), &adc_trajectory_pb);

  // modify trajectory relative time due to the timestamp change in header
  const double dt = start_time - adc_trajectory_pb.header().timestamp_sec();
```

**Comment by lihaoxiang1989** [comment]
@qwetqwe I agree with this. Can I modify it from here? or make another PR? :)

**Comment by lihaoxiang1989** [comment]
> Thanks for you PR. This may be a history bug. on_lane_planning has recorded start_timestamp:
> 
> > https://github.com/ApolloAuto/apollo/blob/e076feecb46232bacdf08490c5ff213832e6bdd8/modules/planning/on_lane_planning.cc#L131
> 
> It will be better to change like this:
> 
> ```c++
>   planning_base_->RunOnce(local_view_, &adc_trajectory_pb);
>   auto start_time = adc_trajectory_pb.header().timestamp_sec();
>   common::util::FillHeader(node_->Name(), &adc_trajectory_pb);
> 
>   // modify trajectory relative time due to the timestamp change in header
>   const double dt = start_time - adc_trajectory_pb.header().timestamp_sec();
> ```

Based on your advice, I made another PR for this issue. Pls check

**Pull request closed without merging**
