### PR TITLE
CHECK_NOTNULL to CHECK

### PR DESCRIPTION
**Pull request by geoffviola**
It's better to use CHECK_NOTNULL, when the pointer is being used on the same line. There are gcc warnings, when compiling DCHECK_NOTNULL with optimization: https://github.com/google/glog/blob/master/src/glog/logging.h.in#L1061.

The transformation was applied with

```
git grep -l 'CHECK_NOTNULL' | xargs sed -i -r 's/CHECK_NOTNULL\(([^)]+)\);/CHECK(\1);/g'
```

on mac (BSD sed), it's
```
git grep -l 'CHECK_NOTNULL' | xargs sed -i '' -E 's/CHECK_NOTNULL\(([^)]+)\);/CHECK(\1);/g'
```

### CODE REVIEW

**Comment by xiaoxq** [comment]
Actually I suggest removing CHECK the output parameter of functions:
void Func(const InputType& input, Output* output);

IMHO it's a global practice everywhere and in most occasions it's the caller's responsibility to guarantee a valid output pointer. So we can simply remove these checks to make code shorter.

**Comment by geoffviola** [comment]
The intention of the current MR is to remove warnings when building with optimization.

@xiaoxq What about input/output parameters? Should they also not have a check? This change touches a lot of files, it might be good to change things incrementally.

**Comment by lianglia-apollo** [comment]
> The intention of the current PR is to remove warnings when building with optimization.
> 
> @xiaoxq What about input/output parameters? Should they also not have a check? This change touches a lot of files, it might be good to change things incrementally.

The warning from DCHECK is intended, as we don't need those checks in online environment, but need them in off-line mode.

**Comment by geoffviola** [comment]
Don't you want to eliminate the false positive warnings so that other more important one can pop up? For example, "-Wuninitialized" is more active when optimization is enabled.

**Pull request closed without merging**
