### PR TITLE
Docs: add apollo master quick start guide (draft)

### PR DESCRIPTION
**Pull request by storypku**

### CODE REVIEW

**Comment by xiaoxq** [comment]
Let's rename it to "Latest quick start guide" which always describe the master HEAD.
And snapshot it to "Apollo X.X quick start guide" along with each official release.

**Comment by jinghaomiao** [comment]
@storypku It's not yet to release 6.0. Please rename your quick start to be something like "quick_start_new". We'll rename it at the next release.

**Comment by storypku** [comment]
> Let's rename it to "Latest quick start guide" which always describe the master HEAD.
> And snapshot it to "Apollo X.X quick start guide" along with each official release.

Good point.

**Comment by jinghaomiao** [comment]
@storypku create a link from README to this quick document to help developers navigate through to the latest change.

**Comment by storypku** [comment]
> @storypku It's not yet to release 6.0. Please rename your quick start to be something like "quick_start_new". We'll rename it at the next release.

Done.

**Comment by storypku** [comment]
> @storypku create a link from README to this quick document to help developers navigate through to the latest change.

See #11726

**Pull request merged**
