### PR TITLE
#2437

### PR DESCRIPTION
**Pull request by jilinzhou**
add the missing setter function for boolean member variable integrator_hold_ in class PIDController

### CODE REVIEW

**Comment by Capri2014** [comment]
Please sign the CLA, thanks

**Comment by jilinzhou** [comment]
@Capri2014 : If I click the "Details" on the right of license/cls, it shows that I have signed the CLA.

**Comment by Capri2014** [comment]
@jilinzhou  That is strange, let me check it.

**Comment by Capri2014** [comment]
@jilinzhou Clear cache and re-try it?

**Comment by zhxt** [comment]
@jilinzhou hey, could you please [rebase](https://git-scm.com/docs/git-rebase) these there commits into one since it's for one issue, and also add a **meaningful description** for commit summary instead of only with issue number?(#1942)

Use `git log` to see how others do. 

Thanks  :-)

**Pull request closed without merging**
