### PR TITLE
framework: add docs for developer tools and quick start

### PR DESCRIPTION
**Pull request by quning78**

### CODE REVIEW

**Comment by davidhopper2003** [comment]
@quning78 
I used the `cyber_visualizer` tool according to your description and got the following error:
cyber_visualizer_error

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 16.04
- **Apollo installed from (source or binary)**:  from source
- **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:  > 3.0, latest master branch
- **Build command**: `bash apollo.sh build -j 16`

**Comment by quning78** [comment]
> * **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:  > 3.0, latest master branch

@wanglei828 Do you change the OpenGL version inside the release docker?

If not, @GoLancer can take a look at this.

**Comment by quning78** [comment]
> @quning78
> I used the `cyber_visualizer` tool according to your description and got the following error:
> cyber_visualizer_error
> 
> ### System information
> * **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 16.04
> * **Apollo installed from (source or binary)**:  from source
> * **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:  > 3.0, latest master branch
> * **Build command**: `bash apollo.sh build -j 16`

@davidhopper2003 could you open an issue about this problem? thanks!

**Comment by GoLancer** [comment]
@davidhopper2003 Could you post the output of
```
$ lspci -vnn | grep "VGA"
$ pacman -Qs libgl
```

**Comment by davidhopper2003** [comment]
> > @quning78
> > I used the `cyber_visualizer` tool according to your description and got the following error:
> > cyber_visualizer_error
> > ### System information
> > 
> > * **OS Platform and Distribution (e.g., Linux Ubuntu 14.04)**: Linux Ubuntu 16.04
> > * **Apollo installed from (source or binary)**:  from source
> > * **Apollo version (1.0, 1.5, 2.0, 2.5, 3.0)**:  > 3.0, latest master branch
> > * **Build command**: `bash apollo.sh build -j 16`
> 
> @davidhopper2003 could you open an issue about this problem? thanks!
Sure. My pleasure.

**Comment by davidhopper2003** [comment]
> @davidhopper2003 Could you post the output of
> 
> ```
> $ lspci -vnn | grep "VGA"
> $ pacman -Qs libgl
> ```
Here is the output of my computer: 
cyber_visualizer_info1
cyber_visualizer_info2

**Pull request merged**
