### PR TITLE
Perception: fixed a bug in information matrix update step

### PR DESCRIPTION
**Pull request by cedricxie**
A bug is found and corrected in the update step of information matrix.
A few comments are added for clear explanation as well.

### CODE REVIEW

**Comment by techoe** [comment]
Thank you for contributing Apollo. Please check "lint" issues and follow the instructions.

**Comment by weidezhang** [comment]
approved. thx for the fix. there is another reference implementation you can refer to in apollo 2.5 is: 

https://github.com/ApolloAuto/apollo/blob/r2.5.0/modules/perception/obstacle/fusion/probabilistic_fusion/pbf_imf_fusion.cc

Also, the paper we used to implement async fusion is: 

https://ieeexplore.ieee.org/document/6222334

**Comment by xiaoxq** [comment]
For lint issue, please run "./apollo.sh lint" and check log files of the failures.
Thanks!

**Comment by cedricxie** [comment]
@weidezhang Thanks for approving! The reference you provided is very helpful for understanding the fusion strategy.

@techoe @xiaoxq Thank you both for checking! I have updated the coding styles.

**Pull request merged**
