### PR TITLE
Gem

### PR DESCRIPTION
**Pull request by lbucklandAS**
Add range corrections and other fixes for full control of the gem.

### CODE REVIEW

**Comment by lbucklandAS** [comment]
@Capri2014 Hmm I did rebase before pushing, I'll pull it down and resolve.

**Comment by lbucklandAS** [comment]
@Capri2014 Should be resolved.

**Comment by Capri2014** [comment]
@lbucklandAS I still see conflicts here, could you do a 'git pull --rebase upstream gem", after resolving the conflict, do a "git push -f origin gem"?

**Comment by Capri2014** [comment]
@lbucklandAS Hi Lucas, I am closing this one since the additional commit has been picked to the trunk.

**Pull request closed without merging**
