### PR TITLE
Common:Math Utils:add unit tests

### PR DESCRIPTION
**Pull request by SohamGhormade**
Added unit tests for sigmoid,RotateAxis and other math functions in the utilities library.
Updated copyright header.

### CODE REVIEW

**Comment by Capri2014** [comment]
@SohamGhormade Thanks for the contribution! Could you fix the lint error in the commit ? You can run `./apollo.sh check` to make sure you pass all build, test, and lint check before check-in.

**Comment by SohamGhormade** [comment]
@Capri2014 Thank you for catching.
I verified that lint passed for me locally.
i.e the issue should be fixed now.
Thanks!

**Comment by SohamGhormade** [comment]
@Capri2014 
Two side questions:
Is there a check in window for merges in Apollo repo?If yes,from what time to what time?
If you have any suggestions of how I can contribute to the repo it would be appreciated.
I have contributed with unit tests and typos so far.
I am interested particularly in the perception and localization modules but am open to contributing to other modules as well.
Looking forward to hearing from you!
Thanks!

**Comment by SohamGhormade** [comment]
@ycool and @lianglia-apollo thanks for reviewing my pull request and merging it!
If you have any suggestions of how I can contribute to the repo I would highly appreciate it.
Thanks!

Background:

- I have contributed by adding unit tests and fixing typos so far.
- I am interested particularly in the perception and localization modules but am open to contributing to other modules as well.

**Comment by SohamGhormade** [comment]
Thanks both in advance for your time and attention.

**Pull request merged**
