### PR TITLE
Common: add vehicle model for trajectory stitcher

### PR DESCRIPTION
**Pull request by JasonZhou404**
Test would fail now as many init point has a nonzero speed.
Plz have a review before I make any change to testdata.

### CODE REVIEW

**Comment by Capri2014** [comment]
@JasonZhou404 @ycool @YajiaZhang We may want  to merge VehicleState and VehicleModel since they share similar functionalities.

**Comment by Capri2014** [comment]
Also suggest add "Preset" interface to pre-set the initial vehicle model state, and also "Reset" interface. This should be help resolve the failed cases problems mentioned above.

**Comment by YajiaZhang** [comment]
@Capri2014 Actually VehicleModel implemented here is part of VehicleState. It is fine to be integrated in the VehicleState class. 
For the failure cases, the past implementation is wrong and we should not resolve the failure cases due to a wrong model other than updating it.

**Comment by YajiaZhang** [comment]
@JasonZhou404 I will merge the pull request and the modifications can be implemented in future commits.

**Comment by JasonZhou404** [comment]
Maybe wait unitl I make change to the testdata tomorrow?

Yajia Zhang <notifications@github.com>于2019年2月11日 周一21:25写道：

**Comment by JasonZhou404** [comment]
Oh, ok, it is not master anyway

Jinyun Zhou <zhoujiny404@gmail.com>于2019年2月11日 周一21:26写道：

**Pull request merged**
