### PR TITLE
minor fixes.

### PR DESCRIPTION
**Pull request by csukuangfj**
minor fixes.

### CODE REVIEW

**Comment by Capri2014** [comment]
@csukuangfj Please fix the lint issue, more details in https://travis-ci.org/ApolloAuto/apollo/jobs/394282079. Also you can run `./apollo.sh lint` for self check before commit.

**Comment by csukuangfj** [comment]
@Capri2014 
Fixed.
Thank you for the comment.

**Comment by Capri2014** [comment]
@csukuangfj Sorry some conflicts cause by the order of our merge, could you submit an updated one?

**Comment by csukuangfj** [comment]
@Capri2014 

Done.

**Comment by Capri2014** [comment]
@csukuangfj Hi I applied a conflict resolving attached to your commits. Thanks again, and if possible, please break commits that cross many files down to smaller commits to avoid potential conflicts.

**Comment by csukuangfj** [comment]
@Capri2014 
Thank you

**Pull request merged**
