### PR TITLE
 Changes to be committed: some docs about apollo arch and modules.

### PR DESCRIPTION
**Pull request by ahuer2435**
new file:   "docs/howto/arch/adapter\350\256\276\350\256\241\346\236\266\346\236\204\346\272\220\347\240\201\345\210\206\346\236\220.docx"
	new file:   "docs/howto/arch/apollo \347\263\273\347\273\237\346\236\266\346\236\204\346\272\220\347\240\201\345\210\206\346\236\220.docx"
	new file:   docs/howto/arch/hmi_sh__dreamview__rosbag.vsd
	new file:   docs/howto/arch/node_arch.vsd
	new file:   docs/howto/modules/HD map/apollo1.5_HDmap.docx
	new file:   docs/howto/modules/localization/localization module.docx
	new file:   docs/howto/modules/localization/localization module.vsd
	new file:   "docs/howto/modules/perception/3D \347\233\256\346\240\207\346\243\200\346\265\213\344\270\216\350\267\237\350\270\252.docx"
	new file:   docs/howto/modules/perception/node_arch_ture.vsd
	new file:   docs/howto/modules/perception/perception flow.vsd
	new file:   docs/howto/modules/perception/perception module.docx
	new file:   "docs/howto/modules/prediction/prediction\346\250\241\345\235\227\345\210\206\346\236\220.docx"
	new file:   "docs/howto/modules/prediction/\346\250\241\345\235\227\350\212\202\347\202\271.vsd"
	new file:   docs/howto/modules/routing/IO.vsd
	new file:   "docs/howto/modules/routing/routing\346\250\241\345\235\227\345\210\206\346\236\220.docx"

### CODE REVIEW

**Comment by Capri2014** [comment]
@ahuer2435 Can you migrate the documents into .md format? This is the document format we use in Apollo project. You can refer to https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet for more details, and if you are using IDEs like Atom or others, there are standard .md preview packages as well.

**Comment by ahuer2435** [comment]
.md格式可以支持 画图吗？因为文档中有一些用Visio画的流程图。

**Comment by Capri2014** [comment]
@ahuer2435 Yes, you can insert different format of figures into .md file. https://github.com/ApolloAuto/apollo/blob/master/README.md is one good example.

**Comment by ahuer2435** [comment]
好的，我修改下，再提交。

**Comment by lianglia-apollo** [comment]
@ahuer2435 hi, are you still working on this topic?

**Comment by ahuer2435** [comment]
非常抱歉，刚修改完成，正在同步，稍后push。

**Comment by ahuer2435** [comment]
非常抱歉，我git push的时候，提示权限不够，然后看了下本地，如下：

我是在docs_branch分支操作的。

想问下，接下来是否应该如何操作，是重新起一个PR吗？git不太熟悉，不好意思。@lianglia-apollo
@Capri2014

**Comment by ahuer2435** [comment]
重新提交了一个PR： https://github.com/ApolloAuto/apollo/pull/3640

**Pull request closed without merging**
