### PR TITLE
Clarity of text for HowTo

### PR DESCRIPTION
**Pull request by aaronhma**
This is for fixing the clarity of README.md.

### CODE REVIEW

**Comment by aaronhma** [comment]
@natashadsouza Thank you for merging my PR! I am now the youngest Baidu/Apollo/Self Driving Car contributor at 11 years old! (https://www.aaronhma.com) Thanks! 😀

**Comment by natashadsouza** [comment]
@aaronhma that's wonderful! Welcome to the Apollo Family! Hope you continue your contribution streak.. we are all super proud of you!

**Comment by Capri2014** [comment]
@aaronhma Great job! One small thing is you could improve in future commits is that next time please add the commit message in the follow format: `<ModuleNames>: CommitContent`, for instance,  it can be `Docs: Clarity of text for HowTo`, more information about the format could be found in `https://github.com/ApolloAuto/apollo/tree/master/docs/howto`

**Comment by aaronhma** [comment]
@Capri2014 @natashadsouza Thanks!

**Pull request merged**
