### PR TITLE
Planning: cleaning for new fallback caculation

### PR DESCRIPTION
**Pull request by Capri2014**

### CODE REVIEW

**Comment by Capri2014** [comment]
Please do not merge this one

**Comment by JasonZhou404** [comment]
Is it still WIP? Please resolve the conflict?

**Comment by deidaraho** [comment]
> Is it still WIP? Please resolve the conflict?

I am still working on this.

**Comment by Capri2014** [comment]
@JasonZhou404 @deidaraho conflicts resolved and you can use this one as new reference.

**Pull request merged**
