### PR TITLE
Update global_flagfile.txt

### PR DESCRIPTION
**Pull request by gengqx**
Because we could not find any data about sunnyvale_l
and this would cause that we could not open the dreamview,
So I think the default value should be demo in case that other people should debug with dreamview.

### CODE REVIEW

**Comment by xiaoxq** [comment]
sunnyvale_loop is so large that we have to host it in docker image. You should see it after starting the apollo_dev container.

**Comment by ycool** [comment]
Can you check if your env has /home/tmp/modules_data/map/data/sunnyvale_loop/? More details can be found at https://github.com/ApolloAuto/apollo/issues/1543 ?

Thanks.

**Comment by gengqx** [comment]
Yes,I could find the map,but it did not copy to the dev docker.

**Comment by ycool** [comment]
the copy happens at 
https://github.com/ApolloAuto/apollo/blob/master/scripts/docker_adduser.sh#L53

Can you help to debug why the copy step doesn't happen in your env? 

Thanks.

**Comment by ycool** [comment]
I am going to close this pull. please feel free to reopen or add more comments if more issues are found. Thanks.

**Pull request closed without merging**
